-- Create weekly_schedule table
create table if not exists public.weekly_schedule (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  day_of_week int not null, -- 1=Monday, 2=Tuesday, ... 7=Sunday
  is_rest_day boolean default false,
  target_body_part text, -- e.g. "Chest Day", "Legs"
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, day_of_week)
);

-- RLS
alter table public.weekly_schedule enable row level security;

create policy "Users can view their own schedule" on weekly_schedule for select using (auth.uid() = user_id);
create policy "Users can insert their own schedule" on weekly_schedule for insert with check (auth.uid() = user_id);
create policy "Users can update their own schedule" on weekly_schedule for update using (auth.uid() = user_id);
create policy "Users can delete their own schedule" on weekly_schedule for delete using (auth.uid() = user_id);
