-- Run this in the Supabase SQL Editor

-- Create Users Table if it doesn't exist (Supabase handles auth.users automatically, 
-- but if we want a public profile table linked to it)
-- NOTE: For this simple app, we can rely on Supabase Auth, but to minimize refactoring, 
-- let's use a public 'users' table or just map 'auth.users'.
-- actually, standard supabase auth is best. I will adapt the store to use supabase user.

-- Exercises Table
create table public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  category text null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Workout Sessions Table
create table public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  exercise_id bigint references public.exercises not null,
  workout_date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Workout Sets Table
create table public.workout_sets (
  id bigint generated by default as identity primary key,
  session_id bigint references public.workout_sessions on delete cascade not null,
  weight numeric default 0,
  reps integer default 0,
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.exercises enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_sets enable row level security;

-- Policies (Allow all for now for simplicity, or specific user policies)
-- Exercises: Public read, Authenticated create/update
create policy "Exercises are public" on exercises for select using (true);
create policy "Users can add exercises" on exercises for insert with check (auth.role() = 'authenticated');
create policy "Users can update exercises" on exercises for update using (auth.role() = 'authenticated');
create policy "Users can delete exercises" on exercises for delete using (auth.role() = 'authenticated');

-- Workouts: Users can only see their own
create policy "Users can see own sessions" on workout_sessions for select using (auth.uid() = user_id);
create policy "Users can insert own sessions" on workout_sessions for insert with check (auth.uid() = user_id);
create policy "Users can delete own sessions" on workout_sessions for delete using (auth.uid() = user_id);

-- Sets: Users can see sets belonging to their sessions
-- (Complex join policy, or just simplify for this MVP to 'authenticated')
create policy "Users can see sets" on workout_sets for select using (auth.role() = 'authenticated');
create policy "Users can insert sets" on workout_sets for insert with check (auth.role() = 'authenticated');
create policy "Users can update sets" on workout_sets for update using (auth.role() = 'authenticated');
create policy "Users can delete sets" on workout_sets for delete using (auth.role() = 'authenticated');
